### ISSUE TITLE
Add a project license

### ISSUE THREAD

**Issue by ghost** [bjpop/js-turtle#4]
That's a nice project you've created here!

Unfortunately, from a legal point of view, it's illegal for us to use, modify or redistribute your code, even without a commercial purpose.

I don't think that you intend these restrictions, but this is the common way for all GitHub repositories which do not include a license file.

Therefore, I'd suggest you to add a `LICENSE` file to this repository. If you want to leave it free to everyone, I'd suggest you the OSI-approved 0-clause BSD License: https://tldrlegal.com/license/bsd-0-clause-license

You can then just add this to your LICENSE file:  
```
Copyright (C) <year(s)> <copyright holder(s)>

Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
```

Thanks!

**Comment by bjpop** [comment]
Good idea @famecastle 

I've now added the 3-Clause BSD License:

https://github.com/bjpop/js-turtle/commit/0c5f86be072962ba9f47810c490a24cb9e09db87

Cheers!

**Comment by ghost** [comment]
Great, thanks for this nice repo.
